import { createServer } from "node:http";
import { randomUUID } from "node:crypto";
import "dotenv/config";
import {
  createDataset,
  getChatMessages,
  getCurrentDataset,
  getDatabasePath,
  getDatasetById,
  patchDatasetRow,
  saveChatMessages,
} from "./database/dataset-repository.js";
import {
  buildDatasetSchema,
  createChatResponse,
  generateCorrelationAnalysis,
  generateDemoDataset,
  normalizeColumns,
} from "./services/analytics-service.js";
import { aiAnalyzer } from "./services/ai-analyzer.js";
import { buildUnifiedSchema } from "./services/data-merger.js";
import { smartAutoChartGenerationForSingle, smartAutoChartGenerationForMerged, classifyColumns, buildEnhancedSchema } from "./services/schema-detector.js";

const port = Number(process.env.PORT || 3001);

const sendJson = (response, statusCode, payload) => {
  response.writeHead(statusCode, {
    "Content-Type": "application/json; charset=utf-8",
    "Access-Control-Allow-Origin": "*",
    "Access-Control-Allow-Headers": "Content-Type",
    "Access-Control-Allow-Methods": "GET,POST,PATCH,OPTIONS",
  });
  response.end(JSON.stringify(payload));
};

const readJsonBody = async (request) =>
  new Promise((resolve, reject) => {
    let body = "";

    request.on("data", (chunk) => {
      body += chunk;
      if (body.length > 500 * 1024 * 1024) {
        reject(new Error("Request body too large"));
        request.destroy();
      }
    });

    request.on("end", () => {
      if (!body) {
        resolve({});
        return;
      }

      try {
        resolve(JSON.parse(body));
      } catch {
        reject(new Error("Invalid JSON body"));
      }
    });

    request.on("error", reject);
  });

const buildState = async () => {
  const dataset = getCurrentDataset();
  let analysis = null;
  
  if (dataset && dataset.rows && dataset.rows.length > 0) {
    try {
      const schema = buildEnhancedSchema(dataset.columns, dataset.rows);
      
      let autoGeneratedCharts = [];
      try {
        const columnClassification = classifyColumns(dataset.rows);
        autoGeneratedCharts = smartAutoChartGenerationForSingle(dataset.rows, columnClassification);
      } catch (autoError) {
        console.warn('Auto chart generation failed:', autoError.message);
      }
      
      const allCharts = [
        ...(autoGeneratedCharts.filter(c => c !== null)),
        ...(schema.recommendedCharts || [])
      ];
      const seen = new Set();
      const uniqueCharts = allCharts.filter(chart => {
        if (seen.has(chart.title)) return false;
        seen.add(chart.title);
        return true;
      }).slice(0, 12);
      
      analysis = {
        dataType: schema.dataType,
        dataTypeLabel: schema.dataTypeLabel,
        chartRecommendations: uniqueCharts,
        insights: schema.insights || []
      };
    } catch (e) {
      console.error('State analysis error:', e.message);
    }
  }
  
  return {
    dataset,
    chatMessages: dataset ? getChatMessages(dataset.id) : [],
    analysis
  };
};

const buildIndexPayload = () => {
  const state = buildState();

  return {
    name: "InsightFlow Local API",
    status: "ok",
    currentDataset: state.dataset
      ? {
          id: state.dataset.id,
          name: state.dataset.name,
          rowCount: state.dataset.rowCount,
          columnCount: state.dataset.columns.length,
        }
      : null,
    routes: {
      health: "GET /api/health",
      state: "GET /api/state",
      importDataset: "POST /api/datasets/import",
      loadDemo: "POST /api/datasets/demo",
      datasetSchema: "GET /api/datasets/:datasetId/schema",
      updateRow: "PATCH /api/datasets/:datasetId/rows/:rowId",
      chat: "POST /api/datasets/:datasetId/chat",
    },
  };
};

const server = createServer(async (request, response) => {
  if (!request.url) {
    sendJson(response, 400, { error: "Missing request URL" });
    return;
  }

  if (request.method === "OPTIONS") {
    sendJson(response, 204, {});
    return;
  }

  const url = new URL(request.url, `http://${request.headers.host || "127.0.0.1"}`);
  const { pathname } = url;

  try {
    if (request.method === "GET" && pathname === "/") {
      sendJson(response, 200, buildIndexPayload());
      return;
    }

    if (request.method === "GET" && pathname === "/api/health") {
      sendJson(response, 200, {
        status: "ok",
        databasePath: getDatabasePath(),
      });
      return;
    }

    if (request.method === "GET" && pathname === "/api/state") {
      const state = await buildState();
      sendJson(response, 200, state);
      return;
    }

    if (request.method === "POST" && pathname === "/api/datasets/demo") {
      const demoDataset = generateDemoDataset();
      const dataset = createDataset({
        name: demoDataset.name,
        fileName: demoDataset.fileName,
        columns: demoDataset.columns,
        rows: demoDataset.rows,
        sourceType: demoDataset.sourceType,
      });

      let analysisResult = null;
      try {
        analysisResult = await aiAnalyzer.analyzeDataset(demoDataset.columns, demoDataset.rows);
      } catch (error) {
        console.error('Demo AI analysis error:', error.message);
      }

      if (!analysisResult) {
        try {
          const schema = buildEnhancedSchema(demoDataset.columns, demoDataset.rows);
          analysisResult = {
            schema,
            chartRecommendations: schema.recommendedCharts || [],
            insights: schema.insights || []
          };
        } catch (e) {
          console.error('Schema detection error:', e.message);
        }
      }

      let autoGeneratedCharts = [];
      try {
        const columnClassification = classifyColumns(demoDataset.rows);
        autoGeneratedCharts = smartAutoChartGenerationForSingle(demoDataset.rows, columnClassification);
      } catch (autoError) {
        console.warn('Auto chart generation failed:', autoError.message);
      }

      const allCharts = [
        ...(autoGeneratedCharts.filter(c => c !== null)),
        ...(analysisResult?.chartRecommendations || [])
      ];
      const seen = new Set();
      const uniqueCharts = allCharts.filter(chart => {
        if (seen.has(chart.title)) return false;
        seen.add(chart.title);
        return true;
      }).slice(0, 12);

      sendJson(response, 201, { 
        dataset, 
        chatMessages: [],
        pipeline: 'demo', 
        analysis: analysisResult ? {
          dataType: analysisResult.schema?.dataType || 'SALES',
          dataTypeLabel: analysisResult.schema?.dataTypeLabel || 'Sales Data',
          chartRecommendations: uniqueCharts,
          insights: analysisResult.insights || [],
          aiInsights: analysisResult.aiInsights || null
        } : null
      });
      return;
    }

    if (request.method === "POST" && pathname === "/api/datasets/import") {
      const body = await readJsonBody(request);
      const rows = Array.isArray(body.rows) ? body.rows : [];

      if (rows.length === 0) {
        sendJson(response, 400, { error: "Dataset must contain at least one row" });
        return;
      }

      const columns = normalizeColumns(rows, Array.isArray(body.columns) ? body.columns : []);
      const dataset = createDataset({
        name: body.name || "Uploaded Dataset",
        fileName: body.fileName || null,
        columns,
        rows,
        sourceType: body.sourceType || "upload",
      });

      let analysisResult = null;
      try {
        analysisResult = await aiAnalyzer.analyzeDataset(columns, rows);
      } catch (error) {
        console.error('Import AI analysis error:', error.message);
      }

      let autoGeneratedCharts = [];
      try {
        const columnClassification = classifyColumns(rows);
        autoGeneratedCharts = smartAutoChartGenerationForSingle(rows, columnClassification);
        console.log('[IMPORT] Smart charts generated:', autoGeneratedCharts.length);
      } catch (autoError) {
        console.warn('Auto chart generation failed:', autoError.message);
      }

      if (!analysisResult) {
        try {
          const schema = buildEnhancedSchema(columns, rows);
          analysisResult = {
            schema,
            chartRecommendations: schema.recommendedCharts || [],
            insights: schema.insights || []
          };
        } catch (e) {
          console.error('Import schema detection error:', e.message);
        }
      }

      const allCharts = [
        ...(autoGeneratedCharts.filter(c => c !== null)),
        ...(analysisResult?.chartRecommendations || [])
      ];
      const seen = new Set();
      const uniqueCharts = allCharts.filter(chart => {
        if (seen.has(chart.title)) return false;
        seen.add(chart.title);
        return true;
      }).slice(0, 15);

      sendJson(response, 201, { 
        dataset, 
        chatMessages: [],
        pipeline: 'single-file',
        analysis: analysisResult ? {
          dataType: analysisResult.schema?.dataType || 'GENERAL',
          dataTypeLabel: analysisResult.schema?.dataTypeLabel || 'Uploaded Data',
          chartRecommendations: uniqueCharts,
          insights: analysisResult.insights || [],
          aiInsights: analysisResult.aiInsights || null
        } : null
      });
      return;
    }

    if (request.method === "POST" && pathname === "/api/datasets/merge") {
      const body = await readJsonBody(request);
      const datasets = Array.isArray(body.datasets) ? body.datasets : [];

      if (datasets.length === 0) {
        sendJson(response, 400, { error: "At least one dataset is required" });
        return;
      }

      if (datasets.length === 1) {
        const rows = datasets[0].rows || [];
        const columns = normalizeColumns(rows, datasets[0].columns || []);
        const dataset = createDataset({
          name: datasets[0].name || "Uploaded Dataset",
          fileName: datasets[0].fileName || null,
          columns,
          rows,
          sourceType: "upload",
        });

        let analysisResult = null;
        try {
          analysisResult = await aiAnalyzer.analyzeDataset(columns, rows);
        } catch (error) {
          console.error('Merge single AI analysis error:', error.message);
        }

        if (!analysisResult) {
          try {
            const { buildEnhancedSchema } = await import('./services/schema-detector.js');
            const schema = buildEnhancedSchema(columns, rows);
            analysisResult = {
              schema,
              chartRecommendations: schema.recommendedCharts || [],
              insights: schema.insights || []
            };
          } catch (e) {}
        }

        sendJson(response, 201, {
          dataset,
          chatMessages: [],
          analysis: analysisResult ? {
            dataType: analysisResult.schema?.dataType || 'GENERAL',
            dataTypeLabel: analysisResult.schema?.dataTypeLabel || 'Merged Data',
            chartRecommendations: analysisResult.chartRecommendations || [],
            insights: analysisResult.insights || []
          } : null
        });
        return;
      }

      console.log('[MERGE] Processing', datasets.length, 'datasets');
      const unified = buildUnifiedSchema(datasets);
      
      if (!unified || !unified.mergedDataset) {
        sendJson(response, 400, { error: "Failed to merge datasets" });
        return;
      }

      const mergedDataset = unified.mergedDataset;
      const mergedColumns = normalizeColumns(mergedDataset.rows, mergedDataset.columns);
      
      const dataset = createDataset({
        name: mergedDataset.name,
        fileName: JSON.stringify(datasets.map(d => d.fileName || d.name)),
        columns: mergedColumns,
        rows: mergedDataset.rows,
        sourceType: "merged",
      });

      console.log('[MERGE] Running AI analysis on', mergedColumns.length, 'columns,', mergedDataset.rows.length, 'rows');

      let analysisResult = null;
      try {
        analysisResult = await aiAnalyzer.analyzeDataset(mergedColumns, mergedDataset.rows);
        if (analysisResult?.schema) {
          analysisResult.schema.dataTypeLabel = mergedDataset.name;
        }
      } catch (error) {
        console.error('Merge AI analysis error:', error.message);
      }

      if (!analysisResult) {
        try {
          const { buildEnhancedSchema } = await import('./services/schema-detector.js');
          const schema = buildEnhancedSchema(mergedColumns, mergedDataset.rows);
          schema.dataTypeLabel = mergedDataset.name;
          analysisResult = {
            schema,
            chartRecommendations: schema.recommendedCharts || [],
            insights: schema.insights || []
          };
        } catch (e) {
          console.error('Merge schema detection error:', e.message);
        }
      }

      const finalDataType = analysisResult?.schema?.dataType || unified.detectedDataTypes?.[0]?.type || 'GENERAL';
      const finalDataTypeLabel = analysisResult?.schema?.dataTypeLabel || 'Merged Dataset';

      const mergeSummary = { type: 'summary', title: 'Merge Summary', message: `Combined ${datasets.length} datasets with ${mergedDataset.rows.length} total rows and ${mergedColumns.length} columns` };
      const allInsights = [mergeSummary, ...(analysisResult?.insights || [])];

      sendJson(response, 201, {
        dataset,
        chatMessages: [],
        analysis: analysisResult ? {
          dataType: finalDataType,
          dataTypeLabel: finalDataTypeLabel,
          chartRecommendations: analysisResult.chartRecommendations || [],
          insights: allInsights,
          aiInsights: analysisResult.aiInsights || null,
          mergeInfo: {
            originalDatasets: datasets.length,
            totalRows: mergedDataset.rows.length,
            commonColumns: unified.summary.commonColumns,
            uniqueColumns: unified.summary.uniqueColumns,
            detectedDataTypes: unified.detectedDataTypes
          }
        } : null
      });
      return;
    }

    const rowMatch = pathname.match(/^\/api\/datasets\/([^/]+)\/rows\/([^/]+)$/);
    if (request.method === "PATCH" && rowMatch) {
      const [, datasetId, rowIdValue] = rowMatch;
      const body = await readJsonBody(request);

      if (!body.column) {
        sendJson(response, 400, { error: "Column is required" });
        return;
      }

      const dataset = patchDatasetRow({
        datasetId,
        rowId: Number(rowIdValue),
        column: body.column,
        value: body.value,
      });

      if (!dataset) {
        sendJson(response, 404, { error: "Row not found" });
        return;
      }

      sendJson(response, 200, { dataset });
      return;
    }

    const schemaMatch = pathname.match(/^\/api\/datasets\/([^/]+)\/schema$/);
    if (request.method === "GET" && schemaMatch) {
      const [, datasetId] = schemaMatch;
      const dataset = getDatasetById(datasetId);

      if (!dataset) {
        sendJson(response, 404, { error: "Dataset not found" });
        return;
      }

      sendJson(response, 200, { schema: buildDatasetSchema(dataset) });
      return;
    }

    const chatMatch = pathname.match(/^\/api\/datasets\/([^/]+)\/chat$/);
    if (request.method === "POST" && chatMatch) {
      const [, datasetId] = chatMatch;
      const body = await readJsonBody(request);
      const query = String(body.query || "").trim();

      if (!query) {
        sendJson(response, 400, { error: "Query is required" });
        return;
      }

      const dataset = getDatasetById(datasetId);
      if (!dataset) {
        sendJson(response, 404, { error: "Dataset not found" });
        return;
      }

      const analysis = await createChatResponse(dataset, query);
      const now = new Date().toISOString();
      const userMessage = {
        id: randomUUID(),
        role: "user",
        content: query,
        timestamp: now,
      };
      const assistantMessage = {
        id: randomUUID(),
        role: "assistant",
        content: analysis.content,
        sql: analysis.sql,
        chart: analysis.chart,
        insights: analysis.insights,
        timestamp: now,
      };

      saveChatMessages(datasetId, [userMessage, assistantMessage]);
      sendJson(response, 201, { userMessage, assistantMessage });
      return;
    }

    const aiCorrMatch = pathname.match(/^\/api\/datasets\/([^/]+)\/ai-correlations$/);
    if (request.method === "GET" && aiCorrMatch) {
      const [, datasetId] = aiCorrMatch;
      const dataset = getDatasetById(datasetId);

      if (!dataset) {
        sendJson(response, 404, { error: "Dataset not found" });
        return;
      }

      const correlationResult = generateCorrelationAnalysis(dataset);
      sendJson(response, 200, correlationResult);
      return;
    }

    const analyzeMatch = pathname.match(/^\/api\/datasets\/([^/]+)\/analyze$/);
    if (request.method === "GET" && analyzeMatch) {
      const [, datasetId] = analyzeMatch;
      const dataset = getDatasetById(datasetId);

      if (!dataset) {
        sendJson(response, 404, { error: "Dataset not found" });
        return;
      }

      const analysis = await aiAnalyzer.analyzeDataset(dataset.columns, dataset.rows);
      sendJson(response, 200, analysis);
      return;
    }

    const autoChartsMatch = pathname.match(/^\/api\/datasets\/([^/]+)\/auto-charts$/);
    if (request.method === "GET" && autoChartsMatch) {
      const [, datasetId] = autoChartsMatch;
      const dataset = getDatasetById(datasetId);

      if (!dataset) {
        sendJson(response, 404, { error: "Dataset not found" });
        return;
      }

      const analysis = await aiAnalyzer.analyzeDataset(dataset.columns, dataset.rows);
      const columnClassification = classifyColumns(dataset.rows);
      const smartCharts = smartAutoChartGenerationForSingle(dataset.rows, columnClassification);
      
      const combinedCharts = [
        ...smartCharts.filter(c => c !== null),
        ...analysis.chartRecommendations.filter(c => c !== null)
      ];

      sendJson(response, 200, {
        charts: combinedCharts,
        insights: analysis.insights,
        aiInsights: analysis.aiInsights,
        dataType: analysis.schema.dataType,
        columnClassification,
        pipeline: 'single-file'
      });
      return;
    }

    const queryContextMatch = pathname.match(/^\/api\/datasets\/([^/]+)\/query-context$/);
    if (request.method === "POST" && queryContextMatch) {
      const [, datasetId] = queryContextMatch;
      const dataset = getDatasetById(datasetId);

      if (!dataset) {
        sendJson(response, 404, { error: "Dataset not found" });
        return;
      }

      const body = await readJsonBody(request);
      const query = String(body.query || "").trim();

      if (!query) {
        sendJson(response, 400, { error: "Query is required" });
        return;
      }

      const contextAnalysis = await aiAnalyzer.analyzeQueryContext(dataset, query);
      sendJson(response, 200, contextAnalysis);
      return;
    }

    const mergeMatch = pathname.match(/^\/api\/datasets\/merge$/);
    if (request.method === "POST" && mergeMatch) {
      const body = await readJsonBody(request);
      const datasets = Array.isArray(body.datasets) ? body.datasets : [];
      
      if (datasets.length === 0) {
        sendJson(response, 400, { error: "No datasets provided to merge" });
        return;
      }

      if (datasets.length === 1) {
        const rows = Array.isArray(datasets[0].rows) ? datasets[0].rows : [];
        const columns = normalizeColumns(rows, Array.isArray(datasets[0].columns) ? datasets[0].columns : []);
        const dataset = createDataset({
          name: datasets[0].name || "Uploaded Dataset",
          fileName: datasets[0].fileName || null,
          columns,
          rows,
          sourceType: "upload",
        });
        const analysis = await aiAnalyzer.analyzeDataset(columns, rows);
        const columnClassification = classifyColumns(rows);
        const smartCharts = smartAutoChartGenerationForSingle(rows, columnClassification);
        
        const combinedCharts = [
          ...smartCharts.filter(c => c !== null),
          ...analysis.chartRecommendations.filter(c => c !== null)
        ];
        
        sendJson(response, 201, { 
          dataset, 
          chatMessages: [],
          merged: false,
          pipeline: 'single-file',
          autoAnalysis: {
            dataType: analysis.schema.dataType,
            charts: combinedCharts,
            insights: analysis.insights,
            aiInsights: analysis.aiInsights,
            columnClassification
          }
        });
        return;
      }

      const unifiedResult = buildUnifiedSchema(datasets);
      if (!unifiedResult) {
        sendJson(response, 400, { error: "Failed to merge datasets" });
        return;
      }

      const { mergedDataset } = unifiedResult;
      const columns = normalizeColumns(mergedDataset.rows, mergedDataset.columns);
      const dataset = createDataset({
        name: mergedDataset.name,
        fileName: mergedDataset.sourceFiles?.join(', ') || null,
        columns,
        rows: mergedDataset.rows,
        sourceType: "merged",
      });

      const analysis = await aiAnalyzer.analyzeDataset(columns, mergedDataset.rows);
      const columnClassification = classifyColumns(mergedDataset.rows);
      const smartCharts = smartAutoChartGenerationForMerged(mergedDataset.rows, columnClassification);
      
      const combinedCharts = [
        ...smartCharts.filter(c => c !== null),
        ...analysis.chartRecommendations.filter(c => c !== null)
      ];
      
      sendJson(response, 201, { 
        dataset, 
        chatMessages: [],
        merged: true,
        pipeline: 'multi-file-merged',
        mergeInfo: {
          originalDatasets: unifiedResult.summary.totalDatasets,
          totalColumns: unifiedResult.summary.totalColumns,
          commonColumns: unifiedResult.summary.commonColumns,
          columnAnalysis: unifiedResult.columnAnalysis,
          detectedDataTypes: unifiedResult.detectedDataTypes
        },
        autoAnalysis: {
          dataType: analysis.schema.dataType,
          charts: combinedCharts,
          insights: analysis.insights,
          aiInsights: analysis.aiInsights,
          columnClassification
        }
      });
      return;
    }

    sendJson(response, 404, { error: "Route not found" });
  } catch (error) {
    sendJson(response, 500, {
      error: error instanceof Error ? error.message : "Internal server error",
    });
  }
});

server.listen(port, () => {
  console.log(`InsightFlow API listening on http://127.0.0.1:${port}`);
});
