import { Sparkles } from "lucide-react";
import type { PremiumInsight } from "@/features/dashboard/types/premiumDashboardTypes";

const toneClass = {
  gold: "border-amber-400/20 bg-amber-500/10 text-amber-200",
  cyan: "border-cyan-400/20 bg-cyan-500/10 text-cyan-200",
  violet: "border-violet-400/20 bg-violet-500/10 text-violet-200",
  emerald: "border-emerald-400/20 bg-emerald-500/10 text-emerald-200",
};

export function PremiumInsightCards({ insights }: { insights: PremiumInsight[] }) {
  return (
    <section className="rounded-2xl border border-violet-400/20 bg-slate-950/80 p-4">
      <div className="mb-4 flex items-center gap-2">
        <span className="grid h-7 w-7 place-items-center rounded-lg bg-violet-500/20 text-violet-200"><Sparkles className="h-4 w-4" aria-hidden="true" /></span>
        <div>
          <h3 className="text-sm font-bold text-white">AI Generated Insights</h3>
          <p className="text-xs text-slate-500">Generated by schema-safe dashboard AI</p>
        </div>
      </div>

      <div className="grid gap-3 md:grid-cols-4">
        {insights.map((insight) => (
          <article key={insight.id} className={`rounded-xl border p-4 ${toneClass[insight.tone]}`}>
            <h4 className="text-sm font-semibold">{insight.title}</h4>
            <p className="mt-2 min-h-12 text-xs leading-5 text-slate-300">{insight.message}</p>
            {insight.action && <button className="mt-3 rounded-lg border border-current/20 px-3 py-1.5 text-[11px] font-semibold" type="button">{insight.action}</button>}
          </article>
        ))}
      </div>
    </section>
  );
}
